[packages]
libx11-xcb1 = ""
libdbus-glib-1-2 = ""
libxt6 = ""
libnss3 = ""
libnspr4 = ""
libxdamage1 = ""
libxfixes3 = ""
libxrandr2 = ""
libxcomposite1 = ""
libasound2 = ""
libatk1.0-0 = ""
libatk-bridge2.0-0 = ""
libpango-1.0-0 = ""
libcairo2 = ""
libcups2 = ""
libgbm1 = ""
libexpat1 = ""
libxcb-dri3-0 = ""
libxss1 = ""
libgdk-pixbuf2.0-0 = ""
libgtk-3-0 = ""
libxtst6 = ""
